version: '2'
services:
  # Run prod image
  prod-app-bk:
    container_name: bookmarks-node-prod
    image: defreitas/bookmark-notes:2.9.3
    hostname: bookmarks.mageddo
    ports:
      - 3000:3000
    environment:
      - HOSTNAMES=bookmarks-node.mageddo
      - PROFILE=PROD
      - NODE_ENV=prod
      - NODE_CONFIG_DIR=conf
    volumes:
      - /var/lib/mageddo/bookmarks-node/db:/opt/bookmarks/db
      - /var/lib/mageddo/bookmarks-node/logs:/opt/bookmarks/logs
      - /var/lib/mageddo/bookmarks-node/conf:/opt/bookmarks/conf
    network_mode: bridge

  # compile the whole apk for production
  prod-build-bk:
    extends: prod-app-bk
    build:
      context: .
      args:
        - DOWNLOAD_API_FROM_REMOTE=0

  # compile only the prod api package
  prod-api-build-bk:
    image: golang:1.9
    volumes:
      - $PWD/bk-api:/go/src/bk-api/
      - $PWD/build:/go/build
      - ./VERSION:/VERSION
    command: bash -c "./builder build"
    environment:
      - TERM=xterm
      - BUILD_PATH=/go/build
      - GOPATH=/go
      - APP_PATH=/go/src/bk-api
      - MG_WORK_DIR=/go/src/bk-api
    working_dir: /go/src/bk-api/
    network_mode: bridge

  # useful to run api for development
  prod-api-compiler-bk:
    extends: prod-api-build-bk
    volumes:
      - /var/lib/mageddo/bookmarks-node/db:/opt/bookmarks/db
    command: bash -c "go install -v bk-api/vendor/github.com/mattn/go-sqlite3 && tail -f /dev/null"
    hostname: bk-api.dev

  # run app for development
  dev-app-bk:
    extends: prod-app-bk
    build:
       context: .
       args:
        - DOWNLOAD_API_FROM_REMOTE=0
    container_name: bookmarks-node
    environment:
      - MG_MODE=debug
      - NODE_CONFIG_DIR=conf
      - NODE_ENV=dev
    volumes:
      - ./:/opt/bookmarks
      - ./files/prod:/opt/bookmarks/prod/sql
    command: bash -c 'npm install && tail -f /dev/null'
