version: '2'
services:

### PRODUCTION RUN

# Run prod image
  prod-app-bk:
    image: defreitas/bookmark-notes:2.13.0
    hostname: bookmarks.mageddo
    environment:
      - HOSTNAMES=bookmarks-node.mageddo
      - PROFILE=PROD
      - NODE_ENV=prod
      - NODE_CONFIG_DIR=conf
    volumes:
      - /var/lib/mageddo/bookmarks-node/db:/opt/bookmarks/db
      - /var/lib/mageddo/bookmarks-node/logs:/opt/bookmarks/logs
      - /var/lib/mageddo/bookmarks-node/conf:/opt/bookmarks/conf
    network_mode: bridge
  

## PRODUCTION BUILD

  # compile the whole apk for production
  prod-build-bk:
    extends: prod-app-bk
    build:
      context: .
      args:
        - DOWNLOAD_API_FROM_REMOTE=0

  # compile only the prod api package
  prod-api-build-bk:
    image: golang:1.9
    volumes:
    - $PWD/bk-api:/go/src/bk-api/
    - $PWD:/app
    command: bash -c "/app/builder apply-version && /app/builder build"
    environment:
    - TERM=xterm
    - GOPATH=/go
    - BUILD_PATH=/app/build
    - API_PATH=/go/src/bk-api
    - MG_WORK_DIR=/go/src/bk-api
    working_dir: /app
    network_mode: bridge


  # build the api and make the github release
  prod-ci-deploy:
    extends: prod-api-build-bk
    command: bash -c "/app/builder validate-release || exit 0 && /app/builder apply-version && /app/builder build && /app/builder upload-release"
    environment:
      - CURRENT_BRANCH=$TRAVIS_BRANCH # current branch name
      - REPO_TOKEN=$REPO_TOKEN # github token to deploy the binary
    volumes:
      - $HOME/.gitconfig:/root/.gitconfig

## DEVELOPMENT

  # run app for development
  dev-app-bk:
    extends: prod-app-bk
    build:
       context: .
       args:
        - DOWNLOAD_API_FROM_REMOTE=0
    environment:
      - MG_MODE=debug
      - NODE_CONFIG_DIR=conf
      - NODE_ENV=dev
    volumes:
      - ./:/opt/bookmarks
      - ./files/prod:/opt/bookmarks/prod/sql
    ports:
      - 3000:3000
    command: bash -c 'npm install && tail -f /dev/null'
