version: '2'
services:
  # Run prod image
  prod-app-bk:
    container_name: bookmarks-node-prod
    image: defreitas/bookmark-notes:2.8.0
    hostname: bookmarks.mageddo
    ports:
      - 3000:3000
    environment:
      - HOSTNAMES=bookmarks-node.mageddo
      - PROFILE=PROD
      - NODE_ENV=prod
      - NODE_CONFIG_DIR=conf
    volumes:
      - /var/lib/mageddo/bookmarks-node/db:/opt/bookmarks/db
      - /var/lib/mageddo/bookmarks-node/logs:/opt/bookmarks/logs
      - /var/lib/mageddo/bookmarks-node/conf:/opt/bookmarks/conf
    network_mode: bridge

  # compile the prod app package
  prod-app-build-bk:
    extends: prod-app-bk
    build:
      context: .

  # compile the prod api package
  prod-api-build-bk:
    image: golang:1.7.4
    volumes:
      - $PWD:/app
    command: bash -c "./builder build"
    environment:
      - TERM=xterm
      - GOPATH=/app/bk-api
    working_dir: /app
    network_mode: bridge

  # useful to run api for development
  prod-api-compiler-bk:
    extends: prod-api-build-bk
    volumes:
      - /var/lib/mageddo/bookmarks-node/db:/opt/bookmarks/db
    working_dir: /app/bk-api/src
    command: tail -f /dev/null
    hostname: bk-api.dev

  # run app for development
  dev-app-bk:
    extends: prod-app-bk
    image: node:5.4.0-slim
    environment:
      - MG_MODE=debug
      - NODE_CONFIG_DIR=conf
    volumes:
      - ./:/opt/bookmarks
      - ./files/prod:/opt/bookmarks/prod/sql
    command: bash -c 'npm install && tail -f /dev/null'
